/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.component;

/**
 *
 * @author ADMIN
 */
public class EastMap extends javax.swing.JPanel {

    /**
     * Creates new form EastMap
     */
    public EastMap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grass1 = new javax.swing.JLabel();
        Grass2 = new javax.swing.JLabel();
        Grass3 = new javax.swing.JLabel();
        Grass4 = new javax.swing.JLabel();

        Grass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/grass-01_270x135.png"))); // NOI18N
        Grass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Grass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/grass-01_270x135.png"))); // NOI18N
        Grass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Grass3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/grass-01_270x135.png"))); // NOI18N
        Grass3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Grass4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/grass-01_270x135.png"))); // NOI18N
        Grass4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Grass1)
            .addComponent(Grass2)
            .addComponent(Grass3)
            .addComponent(Grass4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Grass2)
                .addGap(0, 0, 0)
                .addComponent(Grass1)
                .addGap(0, 0, 0)
                .addComponent(Grass4)
                .addGap(0, 0, 0)
                .addComponent(Grass3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Grass1;
    private javax.swing.JLabel Grass2;
    private javax.swing.JLabel Grass3;
    private javax.swing.JLabel Grass4;
    // End of variables declaration//GEN-END:variables
}
