/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.component;

/**
 *
 * @author ADMIN
 */
public class SouthMap extends javax.swing.JPanel {

    /**
     * Creates new form SouthMap
     */
    public SouthMap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Island = new javax.swing.JLabel();
        Rock1 = new javax.swing.JLabel();
        Rock2 = new javax.swing.JLabel();
        Rock3 = new javax.swing.JLabel();
        Rock4 = new javax.swing.JLabel();
        Start = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Island.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/island-01_270x270.png"))); // NOI18N
        Island.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Rock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/rock-01_135x270.png"))); // NOI18N
        Rock1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Rock2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/rock-01_135x270.png"))); // NOI18N
        Rock2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Rock3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/rock-01_135x270.png"))); // NOI18N
        Rock3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Rock4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/rock-01_135x270.png"))); // NOI18N
        Rock4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/start-01_270x270.png"))); // NOI18N
        Start.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Island)
                .addGap(0, 0, 0)
                .addComponent(Rock1)
                .addGap(0, 0, 0)
                .addComponent(Rock2)
                .addGap(0, 0, 0)
                .addComponent(Rock3)
                .addGap(0, 0, 0)
                .addComponent(Rock4)
                .addGap(0, 0, 0)
                .addComponent(Start)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Start)
                    .addComponent(Rock4)
                    .addComponent(Rock3)
                    .addComponent(Rock2)
                    .addComponent(Rock1)
                    .addComponent(Island))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Island;
    private javax.swing.JLabel Rock1;
    private javax.swing.JLabel Rock2;
    private javax.swing.JLabel Rock3;
    private javax.swing.JLabel Rock4;
    private javax.swing.JLabel Start;
    // End of variables declaration//GEN-END:variables
}
