/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.component;

/**
 *
 * @author ADMIN
 */
public class WestMap extends javax.swing.JPanel {

    /**
     * Creates new form WestMap
     */
    public WestMap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fire1 = new javax.swing.JLabel();
        Fire2 = new javax.swing.JLabel();
        Fire3 = new javax.swing.JLabel();
        Fire4 = new javax.swing.JLabel();

        Fire1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/fire-01_270x135.png"))); // NOI18N
        Fire1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Fire2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/fire-01_270x135.png"))); // NOI18N
        Fire2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Fire3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/fire-01_270x135.png"))); // NOI18N
        Fire3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Fire4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/fire-01_270x135.png"))); // NOI18N
        Fire4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fire4)
                    .addComponent(Fire3)
                    .addComponent(Fire2)
                    .addComponent(Fire1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Fire1)
                .addGap(0, 0, 0)
                .addComponent(Fire2)
                .addGap(0, 0, 0)
                .addComponent(Fire3)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Fire4)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fire1;
    private javax.swing.JLabel Fire2;
    private javax.swing.JLabel Fire3;
    private javax.swing.JLabel Fire4;
    // End of variables declaration//GEN-END:variables
}
